GET http://localhost:1000/cards
# gets and filters the cards
###

POST http://localhost:1000/cards/create
# create new card
###

PUT http://localhost:1000/cards/:id
# edits the cards
###

DELETE http://localhost:1000/cards/:id
# deletes cards
###